[tasks.build-wasm]
command = "cargo"
args = ["build", "--bin", "boltless-client", "--target", "wasm32-unknown-unknown", "--release"]

[tasks.wasm-bindgen]
command = "wasm-bindgen"
args = ["--out-dir", "public/pkg", "--target", "web", "target/wasm32-unknown-unknown/release/boltless-client.wasm"]
dependencies = ["build-wasm"]

[tasks.wasm-serve]
command = "nohup"
args = ["wasmedge", "--dir","public","--env","DIR=public","--env","PORT=3030","./dir_env.wasm"]
dependencies = ["wasm-bindgen"]

[config]
default_to_workspace = false
